### ISSUE TITLE
Border around all themes with Gtk 3.22

### ISSUE THREAD

**Issue by logix2** [themix-project/oomox#154]
I'm using Ubuntu 18.04 (Gnome Shell) which has Gtk 3.22.30, and all the themes generated using Oomox have a border around them: [https://i.imgur.com/uGZBcZv.png](https://i.imgur.com/uGZBcZv.png). As you can see, the border is not only present on the actual theme, but also in the Oomox preview and it happens for all presets as far as I can tell.

I'm using Oomox installed from FlatHub (updated today to the latest version).

I also have a question, I thought it's not worth posting as a separate issue: what presets are based on Materia or Arc themes? I seem to only see presets based on Numix.

**Comment by actionless** [comment]
1) set the border to the same color as background to not see it

2) just change first dropdown Theme Style from Numix to Arc or Materia

**Comment by logix2** [comment]
@actionless thanks. The border tweak works. The my Arc / Materia question... there is only Numix in the Theme style dropdown. Should I open a bug for that?

**Comment by actionless** [comment]
are you running on Flatpak?

**Comment by logix2** [comment]
Yes, using the Flatpak from Flathub.

**Comment by actionless** [comment]
here is written the warning what some plugins are disabled due to specifity of how flatpak works:

https://flathub.org/apps/details/com.github.themix_project.Oomox


however because of some issue description didn't updated when i was updating flathub package last time:
https://github.com/themix-project/oomox/blob/master/packaging/com.github.themix_project.Oomox.appdata.xml#L10

cc @nedrichards, mb you have some idea?
