### ISSUE TITLE
Export Telegram Desktop Themes

### ISSUE THREAD

**Issue by joshbarrass** [themix-project/oomox#249]
Telegram Desktop uses quite a simple structure for it's themes; a `colors.tdesktop-palette` plaintext file that describes all the colours to be used in the GUI, and a `background.png`. These are stored in a zip file with the extension changed to `.tdesktop-theme`.

I was thinking this could be implemented as a minor feature in a similar way to the Spotify themes.

I would be comfortable doing the code to implement such a feature, but I think a rusty spoon would be able to make a nicer-looking theme than me. If someone would be able to put a decent theme together that I could use to do this, I'll happily do the rest.

**Comment by actionless** [comment]
it was relatively recently implemented via base16 plugin:
https://github.com/themix-project/oomox/wiki/How-to-import-and-export-Base16-themes-in-Themix-Oomox

feel free to update oomox readme if you'll find it necessary

**Comment by WORD559** [comment]
Oh, I wasn't aware that existed. That's definitely very helpful, and provides basically all of the functionality I was after. This does only provide the `.tdesktop-palette` file, however, rather than a complete `.tdesktop-theme`. I'm happy to leave it if you don't think there's any point, but I think it would be nice if oomox could automate the generation of a background (and hence, a full theme) rather than leaving it to the user.

If you don't think it's worth it I'm happy to close the issue here.

**Comment by actionless** [comment]
i myself not using telegram, so don't have any opinion on this
