### ISSUE TITLE
can't install ubuntu 17.04+ package

### ISSUE THREAD

**Issue by Mumrik93** [themix-project/oomox#291]
I've been trying to install oomox for a few hours now (the 17.04+ version) and there seems to be some sort of issue with the repos. I cant install it trough the software manager/store, I cant install it from Flathub, not from the terminal and now I'm trying to download the package from here and the download gets cancelled after a few minutes. The 18.10 version can be downloaded without issue but it cant be installed on my distro which is 18.04 based (Mint 19.3)

I really cant say what the issue is, but it seems to only affect the 17.04+ version.

**Comment by actionless** [comment]
if you can't install it from flathub (https://flathub.org/apps/details/com.github.themix_project.Oomox) -- contact flatpak support resources

if you can't install it via commandline (https://github.com/themix-project/oomox#debian-ubuntu-linux-mint) -- paste the output here

**Comment by mfreeman72** [comment]
I'm having the same issue. Here is the terminal output:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'oomox' instead of './oomox_1.13.2-1-g23cd8dc8_17.04+.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 oomox : Depends: libgdk-pixbuf2.0-dev but it is not going to be installed
         Depends: libgtk-3-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

So, the current release seems uninstallable through apt on Linux Mint 19.3.

**Comment by actionless** [comment]
installation of built package is being tested right after the package was built

either you not exactly following installation instructions or mint developers broken something in vanilla ubuntu
