### ISSUE TITLE
Errors when trying to export in Arc or Materia

### ISSUE THREAD

**Issue by hrqmonteiro** [themix-project/oomox#301]
I built from source, installed all the dependencies, and the Oomox preset works just fine, but i get these errors when trying to export in:

Arc
![2020 06 01-19 22 36 screenshot](https://user-images.githubusercontent.com/17055027/83460630-440ec380-a43d-11ea-809b-919740518a67.png)

and when i try in Materia: 

![2020 06 01-19 23 26 screenshot](https://user-images.githubusercontent.com/17055027/83460704-67d20980-a43d-11ea-8617-8b0cfd5343f5.png)

Everything he tries to render in this one i got this "Unknown option" error and then it just shows this 'something went wrong'.

Any help?

**Comment by actionless** [comment]
seems a newer version if Inkscape changed their CLI args (`--export-png` in this case)

By default (in Arch, Flatpak) themix-distributed plugins use ReSVG instead of Inkscape

To fix Materia plugin for new Inkscape args you can make a PR to Materia scripts:  https://github.com/nana-4/materia-theme/search?q=render-asset.sh&unscoped_q=render-asset.sh

However for Arc theme there is no way for it to be fixed: https://github.com/themix-project/oomox/issues/293
