### ISSUE TITLE
Alacritty template cannot be generated

### ISSUE THREAD

**Issue by poetician** [themix-project/oomox#392]
On ArcoLinuxL kernel 5.13.5-arch1-1 running i3wm 4.19.1 (2021-02-01)
MSI Armor RX-580 opencl-mesa 21.1.5-1 and xf86-video-amdgpu 19.1.0-2
version: themix-theme-oomox-git 1.12.1.r10.g1812384d-1

Expected behaviour: select Alacritty to display expert options to copy-paste.
Actual behaviour: the Application and Variant buttons do not respond.
Clicking on the Open Homepage button does work.

Is there more info you require? 

Thanks

**Comment by actionless** [comment]
like version of the app itself or any logs, not model of your video card

**Comment by poetician** [comment]
themix-full-git 1.13.3-2

FYI, it works on a separate installation with kernel 5.10.54-1-lts which I'm tied up with configuring atm.

**Comment by actionless** [comment]
thanks, now logs please :)

**Comment by poetician** [comment]
I have this for starters when clicking on a few apps, then Alacritty:

```
❯ oomox-gui &
[1] 35768

╭─ ~ ───────────────────────────────────────────────────── ✔  ≡  11:01:23  ─╮
╰─ themes/oomox-autumn.dunstrc                                                   ─╯
colorschemes/oomox-autumn.theme
colorschemes/oomox-autumn.16.theme
colors/oomox-autumn.vim
themes/oomox-autumn.rasi
themes/oomox-autumn.config
Traceback (most recent call last):
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 218, in _on_app_changed
    config = self.current_app.get_config()
  File "/opt/oomox/plugins/base16/oomox_plugin.py", line 162, in get_config
    with open(config_path) as config_file:
NotADirectoryError: [Errno 20] N'est pas un dossier: '/home/poeticien/.config/oomox/base16/templates/alacritty/templates/config.yaml'
```

**Comment by actionless** [comment]
update themix-gui-git and to latest versions, and make sure commit hash matches the ones from repository, and post the updated log

**Comment by actionless** [comment]
> themix-full-git 1.13.3-2

this is version of metapackage, ffs open aur

**Comment by poetician** [comment]
themix-gui-git 1.13.3.r143.ga3034ebe-1 is installed from the AUR for about the third or fourth time. Whatever presumed conflict appears to have sorted itself out. Thanks ever so much.

But ffs?? Explainl pls if that's not too much trouble ...

**Comment by actionless** [comment]
my point was what reinstalling themix-full-git wouldn't make any difference because as you can see it from its aur page info, it's only a meta-package, which doesn't have any files, only dependencies

regarding problems reinstalling themix-gui-git - that might be some issue with your aur helper then - in such case trying to build it inside clean directory with `makepkg` (the wiki way) or using `pikaur` (one of officially supported ways to install it) could help

generally speaking about `*-git` packages in aur and aur helpers - you most probably would like to use -Syu --aur --devel kind of upgrade for handling those
